let presets = {
  lensFlarey: {
    noiseSeed: 0.622,
    particleSize: 0.0025,
    particleOpacity: 0.05,
    minSpeed: 0.0156,
    maxSpeed: 0.0597,
    numParticles: 2500,
    vMin: 0.0001,
    useAdditiveBlending: false,
    blackbodySaturation: 1.0,
    blackbodyOffset: 0.5,
    blackbodyScale: 2.0,
    useMonochromeParticles: false,
    useBlackbodyColors: true,
    spawnSphereDiameter: 0.5,
    useDepthTest: true,
    useAntialiasing: true,
    useWeightedSphereSampling: true,
  },
  whispy: {
    noiseSeed: 0.622,
    particleSize: 0.0025,
    particleOpacity: 0.05,
    minSpeed: 0.001,
    maxSpeed: 0.01,
    numParticles: 5000,
    vMin: 0.0001,
    useAdditiveBlending: false,
    blackbodySaturation: 1.5,
    blackbodyOffset: 0.5,
    blackbodyScale: 2.0,
    useMonochromeParticles: false,
    useBlackbodyColors: true,
    spawnSphereDiameter: 0.5,
    useDepthTest: true,
    useAntialiasing: true,
    useWeightedSphereSampling: true,
  },
};
