export let presets = {
  default: {
    palette: "default",
    numParticles: 2500,
    vMin: 0.00005,
    maxSpeed: 0.002,
    minSpeed: 0.0001,
    sizeBase: 0.5,
    useAdditiveBlending: false,
    paletteSaturation: 1.0,
    paletteOffset: 0.5,
    paletteScale: 2.0,
    particleOpacity: 0.025,
    useMonochromeParticles: false,
    spawnSphereDiameter: 0.5,
    useDepthTest: true,
    useAntialiasing: true,
    useWeightedSphereSampling: true,
    noiseSeed: Math.random(),
    noiseScale: 1.0,
    noiseType: "SIMPLEX",
    usePerspectiveSizing: false,
    useSineWaveOpacity: false,
    minSineOpacity: 0.0,
    maxSineOpacity: 1.0,
    sineFrequency: 1.0,
    useFlatCurlNoise: false,
    noiseZOffset: 100.0,
    noiseXOffset: 0.0,
    noiseYOffset: 10.0,
    customResolution: false,
    customResolutionX: 2048,
    customResolutionY: 2048,
    cameraDistance: 2,
  },
  lensFlarey: {
    noiseSeed: 0.622,
    sizeBase: 0.5,
    particleOpacity: 0.0125,
    minSpeed: 0.0156,
    maxSpeed: 0.0597,
    // palette: "default",
    numParticles: 2500,
    vMin: 0.0001,
    useAdditiveBlending: false,
    // paletteSaturation: 1.0,
    // paletteOffset: 0.5,
    // paletteScale: 2.0,
    useMonochromeParticles: false,
    spawnSphereDiameter: 0.5,
    useDepthTest: true,
    useAntialiasing: true,
    useWeightedSphereSampling: true,
    noiseScale: 1.0,
    noiseType: "SIMPLEX",
    usePerspectiveSizing: false,
    useSineWaveOpacity: false,
    minSineOpacity: 0.0,
    maxSineOpacity: 1.0,
    sineFrequency: 1.0,
    useFlatCurlNoise: false,
    noiseZOffset: 100.0,
    noiseXOffset: 0.0,
    noiseYOffset: 10.0,
    customResolution: false,
    customResolutionX: 2048,
    customResolutionY: 2048,
    cameraDistance: 2,
  },
  veils: {
    vMin: 0.00005,
    maxSpeed: 0.02,
    minSpeed: 0.0001,
    useAdditiveBlending: false,
    // paletteSaturation: 1.0,
    // paletteOffset: 0.5,
    // paletteScale: 2.0,
    useMonochromeParticles: false,
    spawnSphereDiameter: 0.5,
    useDepthTest: true,
    useAntialiasing: true,
    useWeightedSphereSampling: true,
    noiseScale: 1.0,
    noiseType: "SIMPLEX",
    usePerspectiveSizing: false,
    useSineWaveOpacity: false,
    minSineOpacity: 0.0,
    maxSineOpacity: 1.0,
    sineFrequency: 1.0,
    useFlatCurlNoise: false,
    noiseZOffset: 100.0,
    noiseXOffset: 0.0,
    noiseYOffset: 10.0,
    customResolution: false,
    customResolutionX: 2048,
    customResolutionY: 2048,
    cameraDistance: 2,
    noiseSeed: 0.43851,
    // palette: "default",
    numParticles: 50000,
    sizeBase: 0.25,
    particleOpacity: 0.03,
  },
  whispy: {
    noiseSeed: 0.622,
    sizeBase: 0.25,
    particleOpacity: 0.01,
    minSpeed: 0.001,
    maxSpeed: 0.01,
    // palette: "default",
    numParticles: 5000,
    vMin: 0.0001,
    useAdditiveBlending: false,
    // paletteSaturation: 1.5,
    // paletteOffset: 0.5,
    // paletteScale: 2.0,
    useMonochromeParticles: false,
    spawnSphereDiameter: 0.5,
    useDepthTest: true,
    useAntialiasing: true,
    useWeightedSphereSampling: true,
    noiseScale: 1.0,
    noiseType: "SIMPLEX",
    usePerspectiveSizing: false,
    useSineWaveOpacity: false,
    minSineOpacity: 0.0,
    maxSineOpacity: 1.0,
    sineFrequency: 1.0,
    useFlatCurlNoise: false,
    noiseZOffset: 100.0,
    noiseXOffset: 0.0,
    noiseYOffset: 10.0,
    customResolution: false,
    customResolutionX: 2048,
    customResolutionY: 2048,
    cameraDistance: 2,
  },
  tendrils: {
    noiseSeed: 0.43851,
    // palette: "default",
    numParticles: 2500,
    vMin: 0.00005,
    maxSpeed: 0.002,
    minSpeed: 0.0001,
    sizeBase: 0.5,
    useAdditiveBlending: false,
    // paletteSaturation: 1.0,
    // paletteOffset: 0.5,
    // paletteScale: 2.0,
    particleOpacity: 0.025,
    useMonochromeParticles: false,
    spawnSphereDiameter: 0.5,
    useDepthTest: true,
    useAntialiasing: true,
    useWeightedSphereSampling: true,
    noiseScale: 1.0,
    noiseType: "SIMPLEX",
    usePerspectiveSizing: false,
    useSineWaveOpacity: false,
    minSineOpacity: 0.0,
    maxSineOpacity: 1.0,
    sineFrequency: 1.0,
    useFlatCurlNoise: false,
    noiseZOffset: 100.0,
    noiseXOffset: 0.0,
    noiseYOffset: 10.0,
    customResolution: false,
    customResolutionX: 2048,
    customResolutionY: 2048,
    cameraDistance: 2,
  },
  megatendrils: {
    noiseSeed: 0.47726,
    // palette: "default",
    numParticles: 2500,
    vMin: 0.00005,
    maxSpeed: 0.002,
    minSpeed: 0.0001,
    sizeBase: 0.5,
    useAdditiveBlending: false,
    // paletteSaturation: 1.0,
    // paletteOffset: 0.5,
    // paletteScale: 2.0,
    particleOpacity: 0.025,
    useMonochromeParticles: false,
    spawnSphereDiameter: 0.5,
    useDepthTest: true,
    useAntialiasing: true,
    useWeightedSphereSampling: true,
    noiseScale: 1.0,
    noiseType: "SIMPLEX",
    usePerspectiveSizing: false,
    useSineWaveOpacity: false,
    minSineOpacity: 0.0,
    maxSineOpacity: 1.0,
    sineFrequency: 1.0,
    useFlatCurlNoise: false,
    noiseZOffset: 100.0,
    noiseXOffset: 0.0,
    noiseYOffset: 10.0,
    customResolution: false,
    customResolutionX: 2048,
    customResolutionY: 2048,
    cameraDistance: 2,
  },
};

// GREAT WINDING TENDRIL SEED - 0.43851
